fix: compare versions in the build script

diff --git a/.github/workflows/build-prod-app.yml b/.github/workflows/build-prod-app.yml
--- a/.github/workflows/build-prod-app.yml
+++ b/.github/workflows/build-prod-app.yml
@@ -34,15 +34,20 @@ jobs:
       - name: Compare versions
         id: compare_versions
         run: |
-          current_tag=${{ github.event.release.tag_name }}
-          latest_tag=${{ steps.get_latest_release.outputs.latest_tag }}
-
-          if [[ "$current_tag" != "$(echo -e "$current_tag\n$latest_tag" | sort -V | head -n1)" ]]; then
-            echo "Current tag ($current_tag) is lower than latest tag ($latest_tag). Failing the workflow."
-            exit 1
+        # Remove the 'v' prefix for numeric comparison
+          cur_ver="${current_tag#v}"
+          lat_ver="${latest_tag#v}"
+          
+        # Determine the highest (latest) version of the two
+          highest="$(printf '%s\n%s' "$cur_ver" "$lat_ver" | sort -V | tail -n1)"
+          
+          if [[ "$cur_ver" != "$lat_ver" && "$highest" != "$cur_ver" ]]; then
+          echo "Current tag ($current_tag) is lower than latest tag ($latest_tag). Failing the workflow."
+          exit 1
           else
-            echo "Current tag ($current_tag) is equal or higher than latest tag ($latest_tag). Continuing the workflow."
+          echo "Current tag ($current_tag) is equal or higher than $latest_tag. Continuing the workflow."
           fi
+
       - name: Set up JDK 17
         uses: buildjet/setup-java@v4
         with:
